# Assignment 3

In this assignment you will explore text message data and create models to predict if a message is spam or not. 

In [1]:
import pandas as pd
import numpy as np

spam_data = pd.read_csv('spam.csv')

spam_data['target'] = np.where(spam_data['target']=='spam',1,0)
spam_data.head(10)

text  target
0  Go until jurong point, crazy.. Available only ...       0
1                      Ok lar... Joking wif u oni...       0
2  Free entry in 2 a wkly comp to win FA Cup fina...       1
3  U dun say so early hor... U c already then say...       0
4  Nah I don't think he goes to usf, he lives aro...       0
5  FreeMsg Hey there darling it's been 3 week's n...       1
6  Even my brother is not like to speak with me. ...       0
7  As per your request 'Melle Melle (Oru Minnamin...       0
8  WINNER!! As a valued network customer you have...       1
9  Had your mobile 11 months or more? U R entitle...       1

In [2]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(spam_data['text'], 
                                                    spam_data['target'], 
                                                    random_state=0)

### Question 1
What percentage of the documents in `spam_data` are spam?

*This function should return a float, the percent value (i.e. $ratio * 100$).*

In [3]:
sum(spam_data['target']==1)/len(spam_data)*100

13.406317300789663

In [4]:
def answer_one():

    # YOUR CODE HERE
    #raise NotImplementedError()
    return sum(spam_data['target']==1)/len(spam_data)*100

answer_one()

13.406317300789663

### Question 2

Fit the training data `X_train` using a Count Vectorizer with default parameters.

What is the longest token in the vocabulary?

*This function should return a string.*

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer().fit(X_train)

In [6]:
max([len(i) for i in vect.get_feature_names_out()])

32

In [7]:
[i for i in vect.get_feature_names_out() if len(i)==max([len(i) for i in vect.get_feature_names_out()])][0]

'com1win150ppmx3age16subscription'

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

def answer_two():

    # YOUR CODE HERE
    #raise NotImplementedError()
    return #Your answer here


answer_two()

### Question 3

Fit and transform the training data `X_train` using a Count Vectorizer with default parameters.

Next, fit a fit a multinomial Naive Bayes classifier model with smoothing `alpha=0.1`. Find the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*

In [9]:
X_train_vectorized = vect.transform(X_train)

X_train_vectorized

<4179x7354 sparse matrix of type '<class 'numpy.int64'>'
	with 55130 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score

clfrNB=MultinomialNB(alpha=.1)
model=clfrNB.fit(X_train_vectorized,y_train)
predictions = model.predict_proba(vect.transform(X_test))

print('AUC: ', roc_auc_score(y_test, predictions[:, 1]))

AUC:  0.991545422134696


In [11]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score

def answer_three():

    # YOUR CODE HERE
    #raise NotImplementedError()
    return #Your answer here

answer_three()

### Question 4

Fit and transform the training data `X_train` using a Tfidf Vectorizer with default parameters. The transformed data will be a compressed sparse row matrix where the number of rows is the number of documents in `X_train`, the number of columns is the number of features found by the vectorizer in each document, and each value in the sparse matrix is the tf-idf value. First find the **max** tf-idf value for every feature.

What 20 features have the smallest tf-idf and what 20 have the largest tf-idf among the **max** tf-idf values?

Put these features in two series where each series is sorted by tf-idf value. The index of the series should be the feature name, and the data should be the tf-idf.

The series of 20 features with smallest tf-idfs should be sorted smallest tfidf first, the list of 20 features with largest tf-idfs should be sorted largest first. Any entries with identical tf-ids should appear in lexigraphically increasing order by their feature name in boh series. For example, if the features "a", "b", "c" had the tf-idfs 1.0, 0.5, 1.0 in the series with the largest tf-idfs, then they should occur in the returned result in the order "a", "c", "b" with values 1.0, 1.0, 0.5.

*This function should return a tuple of two series
`(smallest tf-idfs series, largest tf-idfs series)`.*

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Fit the TfidfVectorizer to the training data specifiying a minimum document frequency of 5
vect = TfidfVectorizer().fit(X_train)
#len(X_train_vectorized.get_feature_names_out())

In [13]:
X_train_vectorized = vect.transform(X_train)


In [14]:
feature_names = np.array(vect.get_feature_names_out())

sorted_tfidf_index = X_train_vectorized.max(0).toarray()[0].argsort()

print('Smallest tfidf:\n{}\n'.format(feature_names[sorted_tfidf_index[:20]]))
print('Largest tfidf: \n{}'.format(feature_names[sorted_tfidf_index[:-21:-1]]))

Smallest tfidf:
['sympathetic' 'healer' 'aaniye' 'dependable' 'companion' 'listener'
 'athletic' 'exterminator' 'psychiatrist' 'pest' 'determined' 'chef'
 'courageous' 'stylist' 'psychologist' 'organizer' 'pudunga' 'venaam'
 'diwali' 'mornings']

Largest tfidf: 
['146tf150p' 'havent' 'home' 'okie' 'thanx' 'er' 'anything' 'lei' 'nite'
 'yup' 'thank' 'ok' 'where' 'beerage' 'anytime' 'too' 'done' '645' 'tick'
 'blank']


In [15]:
(list(feature_names[sorted_tfidf_index[:20]]),list(feature_names[sorted_tfidf_index[:-21:-1]]))

(['sympathetic',
  'healer',
  'aaniye',
  'dependable',
  'companion',
  'listener',
  'athletic',
  'exterminator',
  'psychiatrist',
  'pest',
  'determined',
  'chef',
  'courageous',
  'stylist',
  'psychologist',
  'organizer',
  'pudunga',
  'venaam',
  'diwali',
  'mornings'],
 ['146tf150p',
  'havent',
  'home',
  'okie',
  'thanx',
  'er',
  'anything',
  'lei',
  'nite',
  'yup',
  'thank',
  'ok',
  'where',
  'beerage',
  'anytime',
  'too',
  'done',
  '645',
  'tick',
  'blank'])

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

def answer_four():

    # YOUR CODE HERE
    #raise NotImplementedError()
    return #Your answer here

answer_four()

### Question 5

Fit and transform the training data `X_train` using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **3**.

Then fit a multinomial Naive Bayes classifier model with smoothing `alpha=0.1` and compute the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*

In [18]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score
from sklearn.feature_extraction.text import TfidfVectorizer



In [19]:
vect_min3 = TfidfVectorizer(min_df=3).fit(X_train)
X_train_vectorized_min3 = vect_min3.transform(X_train)
clfrNB=MultinomialNB(alpha=.1)
model_min3=clfrNB.fit(X_train_vectorized_min3,y_train)
predictions_min3 = model_min3.predict_proba(vect_min3.transform(X_test))

print('AUC: ', roc_auc_score(y_test, predictions_min3[:, 1]))



AUC:  0.9954968337775665


In [ ]:
def answer_five():

    # YOUR CODE HERE
    raise NotImplementedError()
    return #Your answer here

answer_five()

### Question 6

What is the average length of documents (number of characters) for not spam and spam documents?

*This function should return a tuple (average length not spam, average length spam).*

In [20]:
spam_data[spam_data['target']==1]['text'].apply(lambda x: len(x))

2       155
5       148
8       158
9       154
11      136
       ... 
5537     90
5540    160
5547    160
5566    147
5567    161
Name: text, Length: 747, dtype: int64

In [21]:
def answer_six():

    # YOUR CODE HERE
    #raise NotImplementedError()
    return (spam_data[spam_data['target']==0]['text'].apply(lambda x: len(x)).mean(),
            spam_data[spam_data['target']==1]['text'].apply(lambda x: len(x)).mean())

answer_six()

(71.02362694300518, 138.8661311914324)

<br>
<br>
The following function has been provided to help you combine new features into the training data:

In [22]:
def add_feature(X, feature_to_add):
    """
    Returns sparse feature matrix with added feature.
    feature_to_add can also be a list of features.
    """
    from scipy.sparse import csr_matrix, hstack
    return hstack([X, csr_matrix(feature_to_add).T], 'csr')

In [23]:
X_train_vectorized

<4179x7354 sparse matrix of type '<class 'numpy.float64'>'
	with 55130 stored elements in Compressed Sparse Row format>

In [24]:
X_train_vectorized.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
vect_min5 = TfidfVectorizer(min_df=5, ngram_range=(1,3)).fit(X_train)
X_train_vect_min5 = vect_min5.fit_transform(X_train)
X_test_vect_min5 = vect_min5.transform(X_test)

In [26]:
X_train_vect_min5

<4179x3383 sparse matrix of type '<class 'numpy.float64'>'
	with 63064 stored elements in Compressed Sparse Row format>

In [27]:
X_train_vect_min5.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.20289001,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [28]:
np.array(X_train.str.len())

array([ 31, 130,  66, ..., 147,  62,  82], dtype=int64)

In [29]:
X_train_vect_with_length=add_feature(X_train_vect_min5,np.array(X_train.str.len()))
X_train_vect_with_length.toarray()

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  31.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 130.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  66.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.20289001,
          0.        , 147.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  62.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  82.        ]])

In [30]:
X_test_vect_with_length=add_feature(X_test_vect_min5,np.array(X_test.str.len()))


### Question 7

Fit and transform the training data X_train using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **5**.

Using this document-term matrix and an additional feature, **the length of document (number of characters)**, fit a Support Vector Classification model with regularization `C=10000`. Then compute the area under the curve (AUC) score using the transformed test data.

*Hint: Since probability is set to false, use the model's `decision_function` on the test data when calculating the target scores to use in roc_auc_score*

*This function should return the AUC score as a float.*

In [31]:
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score



In [32]:
clfSVC = SVC(C=10000)
model_min_5=clfSVC.fit(X_train_vect_with_length, y_train)
roc_auc_score(y_test, model_min_5.predict(X_test_vect_with_length))

    

0.9661689557407943

In [33]:
model_min_5.predict(X_test_vect_with_length)

array([0, 0, 0, ..., 0, 0, 1])

In [34]:
model_min_5.decision_function(X_train_vect_with_length)

array([-1.15058533, -1.17400909,  1.00131345, ..., -0.99957731,
       -1.52320004, -1.00121028])

In [35]:
roc_auc_score(y_test, model_min_5.decision_function(X_test_vect_with_length))


0.9963074885829244

In [36]:
X_train_vect_with_length.toarray()

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  31.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 130.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  66.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.20289001,
          0.        , 147.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  62.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  82.        ]])

In [37]:
from sklearn.svm import SVC

def answer_seven():

    # YOUR CODE HERE
    
    vect = TfidfVectorizer(min_df=5)
    X_train_vect = vect.fit_transform(X_train)
    X_test_vect = vect.transform(X_test)
    
    X_train_vect_with_length = add_feature(X_train_vect, X_train.str.len())
    X_test_vect_with_length = add_feature(X_test_vect, X_test.str.len())
    
    clfSVC = SVC(C=10000)
    clfSVC.fit(X_train_vect_with_length, y_train)
    
    return roc_auc_score(y_test, clfSVC.predict(X_test_vect_with_length))

answer_seven()

0.9661689557407943

### Question 8

What is the average number of digits per document for not spam and spam documents?

*Hint: Use `\d` for digit class*

*This function should return a tuple (average # digits not spam, average # digits spam).*

In [ ]:
def answer_eight():

    # YOUR CODE HERE
    raise NotImplementedError()
    return #Your answer here

answer_eight()

In [38]:
spam_data

text  target
0     Go until jurong point, crazy.. Available only ...       0
1                         Ok lar... Joking wif u oni...       0
2     Free entry in 2 a wkly comp to win FA Cup fina...       1
3     U dun say so early hor... U c already then say...       0
4     Nah I don't think he goes to usf, he lives aro...       0
...                                                 ...     ...
5567  This is the 2nd time we have tried 2 contact u...       1
5568              Will Ì_ b going to esplanade fr home?       0
5569  Pity, * was in mood for that. So...any other s...       0
5570  The guy did some bitching but I acted like i'd...       0
5571                         Rofl. Its true to its name       0

[5572 rows x 2 columns]

In [39]:
spam_data[spam_data['target']==1]['text'].str.count(r'\d').mean()

15.759036144578314

In [40]:
X_train.str.count(r'\d')

872      0
831      2
1273     5
3314    14
4929     0
        ..
4931     1
3264    33
1653     0
2607     0
2732     0
Name: text, Length: 4179, dtype: int64

In [41]:
vect_min5 = TfidfVectorizer(min_df=5).fit(X_train)
X_train_vect_min5 = vect_min5.fit_transform(X_train)
X_test_vect_min5 = vect_min5.transform(X_test)

In [42]:
add_feature(X_train_vect_with_length,X_train.str.count(r'\d')).toarray()

array([[  0.,   0.,   0., ...,   0.,  31.,   0.],
       [  0.,   0.,   0., ...,   0., 130.,   2.],
       [  0.,   0.,   0., ...,   0.,  66.,   5.],
       ...,
       [  0.,   0.,   0., ...,   0., 147.,   0.],
       [  0.,   0.,   0., ...,   0.,  62.,   0.],
       [  0.,   0.,   0., ...,   0.,  82.,   0.]])

In [43]:
X_train_vect_with_length_digits=add_feature(X_train_vect_with_length,X_train.str.count(r'\d'))
X_test_vect_with_length_digits=add_feature(X_test_vect_with_length,X_test.str.count(r'\d'))

In [44]:
from sklearn.linear_model import LogisticRegression


In [45]:
lr_model = LogisticRegression(C=100,max_iter=1000).fit(X_train_vect_with_length_digits, y_train)
predictions = lr_model.predict_proba(X_test_vect_with_length_digits)

print('AUC: ', roc_auc_score(y_test, predictions[:,1]))

AUC:  0.9975298371899562


### Question 9

Fit and transform the training data `X_train` using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **5** and using **word n-grams from n=1 to n=3** (unigrams, bigrams, and trigrams).

Using this document-term matrix and the following additional features:
* the length of document (number of characters)
* **number of digits per document**

fit a Logistic Regression model with regularization `C=100` and `max_iter=1000`. Then compute the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*

In [ ]:
from sklearn.linear_model import LogisticRegression

def answer_nine():

    # YOUR CODE HERE
    raise NotImplementedError()
    return #Your answer here

answer_nine()

### Question 10

What is the average number of non-word characters (anything other than a letter, digit or underscore) per document for not spam and spam documents?

*Hint: Use `\w` and `\W` character classes*

*This function should return a tuple (average # non-word characters not spam, average # non-word characters spam).*

In [46]:
(np.mean(spam_data.loc[spam_data['target']==0,'text'].str.count('\W')), 
            np.mean(spam_data.loc[spam_data['target']==1,'text'].str.count('\W')))

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:2: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:2: SyntaxWarning: invalid escape sequence '\W'
C:\Users\anson\AppData\Local\Temp\ipykernel_2080\2068887360.py:1: SyntaxWarning: invalid escape sequence '\W'
  (np.mean(spam_data.loc[spam_data['target']==0,'text'].str.count('\W')),
C:\Users\anson\AppData\Local\Temp\ipykernel_2080\2068887360.py:2: SyntaxWarning: invalid escape sequence '\W'
  np.mean(spam_data.loc[spam_data['target']==1,'text'].str.count('\W')))


(17.29181347150259, 29.041499330655956)

In [47]:
X_train.str.count('\W')

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
C:\Users\anson\AppData\Local\Temp\ipykernel_2080\2268127304.py:1: SyntaxWarning: invalid escape sequence '\W'
  X_train.str.count('\W')


872      8
831     29
1273    16
3314    26
4929    26
        ..
4931    12
3264    34
1653    47
2607    18
2732    21
Name: text, Length: 4179, dtype: int64

In [ ]:
def answer_ten():

    # YOUR CODE HERE
    raise NotImplementedError()
    return #Your answer here

answer_ten()

### Question 11

Fit and transform the **first 2000 rows** of training data X_train using a Count Vectorizer ignoring terms that have a document frequency strictly lower than **5** and using **character n-grams from n=2 to n=5.**

To tell Count Vectorizer to use character n-grams pass in `analyzer='char_wb'` which creates character n-grams only from text inside word boundaries. This should make the model more robust to spelling mistakes.

Using this document-term matrix and the following additional features:
* the length of document (number of characters)
* number of digits per document
* **number of non-word characters (anything other than a letter, digit or underscore.)**

fit a Logistic Regression model with regularization C=100 and max_iter=1000. Then compute the area under the curve (AUC) score using the transformed test data.

Also **find the 10 smallest and 10 largest coefficients from the model** and return them along with the AUC score in a tuple.

The list of 10 smallest coefficients should be sorted smallest first, the list of 10 largest coefficients should be sorted largest first.

The three features that were added to the document term matrix should have the following names should they appear in the list of coefficients:
['length_of_doc', 'digit_count', 'non_word_char_count']

*This function should return a tuple `(AUC score as a float, smallest coefs list, largest coefs list)`.*

In [71]:
from sklearn.feature_extraction.text import CountVectorizer


In [72]:
vect_25 = CountVectorizer(min_df=5, analyzer='char_wb', ngram_range=(2,5)).fit(X_train[:2000])
X_train_vectorized_25_grams = vect_25.transform(X_train[:2000])
X_test_vectorized_25_grams=vect_25.transform(X_test)

In [73]:
add_feature(X_train_vectorized_25_grams,[X_train[:2000].str.len(),X_train[:2000].str.count(r'\d')
                                         ,X_train[:2000].str.count(r'\W')]).toarray()

array([[  0,   0,   0, ...,  31,   0,   8],
       [  0,   0,   0, ..., 130,   2,  29],
       [  0,   0,   0, ...,  66,   5,  16],
       ...,
       [  0,   0,   0, ...,  35,   0,   7],
       [  0,   0,   0, ..., 109,  18,  25],
       [  0,   0,   0, ...,  33,   0,   5]], dtype=int64)

In [74]:
X_train_vect_with_length_digits_nonwords=add_feature(X_train_vectorized_25_grams,[X_train[:2000].str.len(),X_train[:2000].str.count(r'\d')
                                         ,X_train[:2000].str.count(r'\W')])

In [75]:
X_train_vect_with_length_digits_nonwords.toarray()

array([[  0,   0,   0, ...,  31,   0,   8],
       [  0,   0,   0, ..., 130,   2,  29],
       [  0,   0,   0, ...,  66,   5,  16],
       ...,
       [  0,   0,   0, ...,  35,   0,   7],
       [  0,   0,   0, ..., 109,  18,  25],
       [  0,   0,   0, ...,  33,   0,   5]], dtype=int64)

In [76]:
X_test_vect_with_length_digits_nonwords=add_feature(X_test_vectorized_25_grams,[X_test.str.len(),X_test.str.count(r'\d')
                                         ,X_test.str.count(r'\W')]).toarray()
X_test_vect_with_length_digits_nonwords

array([[  0,   0,   0, ...,  50,   0,  10],
       [  0,   0,   0, ...,  18,   0,   4],
       [  0,   0,   0, ..., 221,   0,  46],
       ...,
       [  0,   0,   0, ...,  47,   0,  10],
       [  0,   0,   0, ..., 160,   0,  47],
       [  0,   0,   0, ..., 148,  10,  36]], dtype=int64)

In [77]:
X_train_vect_with_length_digits_nonwords.shape

(2000, 9892)

In [78]:
X_test_vect_with_length_digits_nonwords.shape

(1393, 9892)

In [79]:

from sklearn.linear_model import LogisticRegression

lr2_model = LogisticRegression(C=100,max_iter=1000).fit(X_train_vect_with_length_digits_nonwords, y_train[:2000])
predictions = lr2_model.predict_proba(X_test_vect_with_length_digits_nonwords)

print('AUC: ', roc_auc_score(y_test, predictions[:,1]))

AUC:  0.9931964416073884


In [80]:
lr2_model.coef_

array([[-0.11556066, -0.1640492 , -0.00632225, ..., -0.13361933,
         2.19986811,  0.3984329 ]])

In [81]:
feature_names = np.array(vect_25.get_feature_names_out())
feature_names

array([' !', ' ! ', ' !!', ..., 'û_', 'û_ ', 'û÷'], dtype=object)

In [60]:
feature_names = np.array(vect_25.get_feature_names_out())
sorted_coef_index = lr2_model.coef_[0].argsort()

print('Smallest Coefs:\n{}\n'.format(feature_names[sorted_coef_index[:10]]))
print('Largest Coefs: \n{}'.format(feature_names[sorted_coef_index[-10:-1]]))

Smallest Coefs:
['. ' '..' ' i' 'at' ' m' 'n ' 'he' 'i ' 'ok' '? ']

Largest Coefs: 
['on' ' f' 'es' 's ' 'xt ' ' st' 'xt' 'ne' 'co']


In [ ]:
def answer_eleven():

    # YOUR CODE HERE
    raise NotImplementedError()
    return #Your answer here

answer_eleven()

In [63]:
feature_names[sorted_coef_index[:10]]

array(['. ', '..', ' i', 'at', ' m', 'n ', 'he', 'i ', 'ok', '? '],
      dtype=object)